const adminStyles = {
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "16px",
    marginBottom: "18px",
  },
  title: {
    margin: 0,
    color: "#17202a",
    fontSize: "24px",
  },
  subtitle: {
    margin: "6px 0 0",
    color: "#5d6d7e",
    fontSize: "14px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: "14px",
    marginBottom: "18px",
  },
  card: {
    background: "#fff",
    border: "1px solid #e5e8ec",
    borderRadius: "8px",
    padding: "16px",
    boxShadow: "0 1px 4px rgba(18, 38, 63, 0.06)",
  },
  statLabel: {
    margin: 0,
    color: "#667085",
    fontSize: "13px",
  },
  statValue: {
    margin: "8px 0 0",
    color: "#111827",
    fontSize: "28px",
    fontWeight: 700,
  },
  toolbar: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: "14px",
  },
  input: {
    minWidth: "220px",
    padding: "10px 12px",
    border: "1px solid #d0d5dd",
    borderRadius: "6px",
    fontSize: "14px",
  },
  select: {
    padding: "10px 12px",
    border: "1px solid #d0d5dd",
    borderRadius: "6px",
    background: "#fff",
    fontSize: "14px",
  },
  button: {
    padding: "10px 14px",
    border: "none",
    borderRadius: "6px",
    background: "#146c94",
    color: "#fff",
    cursor: "pointer",
    fontWeight: 600,
  },
  secondaryButton: {
    padding: "10px 14px",
    border: "1px solid #d0d5dd",
    borderRadius: "6px",
    background: "#fff",
    color: "#344054",
    cursor: "pointer",
    fontWeight: 600,
  },
  linkButton: {
    padding: 0,
    border: "none",
    background: "transparent",
    color: "#146c94",
    cursor: "pointer",
    fontWeight: 700,
    textAlign: "left",
  },
  dangerButton: {
    padding: "8px 12px",
    border: "none",
    borderRadius: "6px",
    background: "#c0392b",
    color: "#fff",
    cursor: "pointer",
  },
  cancelBtn: {
    background: "#c0392b",
    color: "#fff",
    border: "none",
    padding: "8px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 600,
  },
  tableWrap: {
    overflowX: "auto",
    background: "#fff",
    border: "1px solid #e5e8ec",
    borderRadius: "8px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "840px",
  },
  th: {
    textAlign: "left",
    padding: "12px",
    background: "#f6f8fa",
    color: "#344054",
    fontSize: "13px",
    borderBottom: "1px solid #e5e8ec",
  },
  td: {
    padding: "12px",
    borderBottom: "1px solid #edf0f2",
    color: "#17202a",
    fontSize: "14px",
    verticalAlign: "top",
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: "999px",
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "capitalize",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))",
    gap: "10px",
    marginBottom: "16px",
  },
  pagination: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    marginTop: "14px",
  },
  label: {
    display: "block",
    marginBottom: "6px",
    color: "#344054",
    fontSize: "13px",
    fontWeight: 700,
  },
  textarea: {
    width: "100%",
    minHeight: "96px",
    padding: "10px 12px",
    border: "1px solid #d0d5dd",
    borderRadius: "6px",
    fontSize: "14px",
    resize: "vertical",
    boxSizing: "border-box",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modalBox: {
    width: "100%",
    maxWidth: "520px",
    background: "#fff",
    borderRadius: "8px",
    padding: "20px",
    boxShadow: "0 20px 40px rgba(15, 23, 42, 0.2)",
  },
};

export default adminStyles;
